class CommandDescription:
  def __init__(
    self,
    name: str,
    preview: str,
    user_command: str,
    short: str,
    long: str,
    add_to_menu: bool = False
  ):
    self.name = name
    self.preview = preview
    self.userCommand = user_command
    self.short = short
    self.long = long
    self.addToMenu = add_to_menu or False
 

global_command_list = [
  CommandDescription(name, preview, user_command, short, long, add_to_menu)
  for name, preview, user_command, short, long, add_to_menu in [
    (
      'help',
      '/help',
      'handleHelp',
      'Помощь',
      'Показывает страницу с подробным объяснением команд (эту)',
      True,
    ),
    (
      'make_event',
      '/make_event',
      'handleMakeEvent',
      'Новое событие',
      'Добавляет новое событие в подключённое расписание',
      True,
    ),
    (
      'edit_event',
      '/edit_event',
      'handleEditEvent',
      'Редактировать событие',
      'Открывает диалог для редактирования выбранного события, принадлежащее подключённому расписанию. Событие выбирается с помощью идентификатора; чтобы узнать идентификатор события, используйте команду /show_events',
      True,
    ),
    (
      'remove_event',
      '/remove_event',
      'handleRemoveEvent',
      'Удалить событие',
      'Удаляет из подключённого расписание событие с указаным идентификатором. Идентификатор события можно узнать с помощью команды /show_events',
      True,
    ),
    (
      'post_preview',
      '/post_preview',
      'handlePostPreview',
      'Показать превью расписания',
      'Отправить пост расписания не в канал, а в чат с вами',
      True,
    ),
    (
      'translate',
      '/translate',
      'handleTranslate',
      'Транслировать расписание в канал',
      'Постит расписание в канал и держит текст актуальным (реагирует на любые операции изменяющие расписания)',
      True,
    ),
    (
      'translate_to_message',
      '/translate_to_message',
      'handleTranslateToMessage',
      'Транслировать расписание в сообщение',
      'Редактирует указанное сообщение и держит его в актуальном состоянии',
      True,
    ),
    (
      'make_timesheet',
      '/make_timesheet',
      'handleMakeTimesheet',
      'Создать расписание',
      'Создаёт новое расписание с указаным именем и паролем. Имя и пароль должны состоять только из латинских букв, цифр и символов нижнего подчёркивания. Имя и пароль будут использоваться для подключения к расписанию с помощью команды /set_timesheet. Подключиться к расписанию может любой пользователь',
      True,
    ),
    (
      'set_timesheet',
      '/set_timesheet',
      'handleSetTimesheet',
      'Подключиться к расписанию',
      'Подключает к расписанию с указаным именем. Для защиты используется пароль: спросите его у создателя расписания',
      True,
    ),
    (
      'set_destination',
      '/set_destination',
      'handleSetDestination',
      'Подключиться к каналу',
      'Устанавливает канал или публичную группу, в который бот будет постить расписание и держать его актуальным',
      True,
    ),
    (
      'show_timesheet_info',
      '/show_timesheet_info',
      'handleShowTimesheetInfo',
      'Информация о расписании',
      'Показывает всю информацию о подключённом расписаниии',
      True,
    ),
    (
      'show_destination_info',
      '/show_destination_info',
      'handleShowDestinationInfo',
      'Информация о канале',
      'Показывает всю информацию о текущем подключении (канале или группе)',
      True,
    ),
    (
      'show_events',
      '/show_events',
      'handleShowEvents',
      'Посмотреть события',
      'Показывает в кратком виде все события, принадлежащие подключённому расписанию; здесь можно узнать id события (предваряется решёткой "#") для команд /edit_event и /remove_event',
      False,
    ),
    (
      'set_destination_head',
      '/set_destination_head',
      'handleSetDestinationHead',
      'Установить заголовок для канала',
      'Устанавливает специфичный для текущего канала или группы специфичный заголовок; для остальных каналов будет браться заголовок, установленный командой /set_timesheet_head',
      False,
    ),
    (
      'set_destination_tail',
      '/set_destination_tail',
      'handleSetDestinationTail',
      'Установить подвал для канала',
      'Устанавливает специфичный для текущего канала или группы специфичный подвал; для остальных каналов будет браться подвал, установленный командой /set_timesheet_tail',
      False,
    ),
    (
      'set_destination_black_list',
      '/set_destination_black_list',
      'handleSetDestinationBlackList',
      'Скрыть из канала мероприятия по ID',
      'Задаёт список мероприятий, которые не должны отображаться в текущем канале или группе',
      False,
    ),
    (
      'set_destination_words_black_list',
      '/set_destination_words_black_list',
      'handleSetDestinationWordsBlackList',
      'Установить бан-слова для канала',
      'Если название мероприятие будет содержать одно из перечисленных слов, устанавливающихся этой командой, мероприятие не будет показано в расписании в данном канале или группе',
      False,
    ),
    (
      'set_timesheet_head',
      '/set_timesheet_head',
      'handleSetTimesheetHead',
      'Установить заголовок расписания',
      'Устанавливает текст, который будет находиться в начале поста с расписанием. Введите специальное значение "none" для удаления',
      False,
    ),
    (
      'set_timesheet_tail',
      '/set_timesheet_tail',
      'handleSetTimesheetTail',
      'Установить подвал расписания',
      'Устанавливает текст, который будет находиться в конце поста с расписанием. Введите специальное значение "none" для удаления',
      False,
    ),
    (
      'show_timesheet_list',
      '/show_timesheet_list',
      'handleShowTimesheetList',
      'Отобразить все существующие расписания',
      'Отображает список названий всех существующих расписаний',
      False,
    ),
    (
      'clear_translations',
      '/clear_translations',
      'handleClearTranslations',
      'Очистить все трансляции в канал',
      'Отключает поддержание постов в канале в актуальном состоянии',
      False,
    ),
    (
      'set_timesheet_event_format',
      '/set_timesheet_event_format',
      'handleSetTimesheetEventFormat',
      'Установить формат события для расписания',
      'Устанавливает формат события для расписания',
      False,
    ),
    (
      'set_destination_event_format',
      '/set_destination_event_format',
      'handleSetDestinationEventFormat',
      'Установить формат события для канала',
      'Устанавливает формат события для канала',
      False,
    ),
    (
      'show_translations',
      '/show_translations',
      'handleShowTranslations',
      'Показать трансляции',
      'Показать трансляци',
      False,
    ),
    (
      'remove_translation',
      '/remove_translation',
      'handleRemoveTranslation',
      'Удалить трансляцию',
      'Удалить трансляцию',
      False,
    ),
    (
      'start',
      '/start',
      'handleStart',
      'Помощь',
      'Запуск бота',
      False,
    ),
  ]
]
